# docker-compose.yml

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consult24-client
    restart: always
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
      # - /usr/src/app/.next
      # - ./:/app
      # - /app/node_modules
      # - /app/.next
    ports:
      - 3000:3000
